#!/usr/bin/env python3
"""Standalone visualization for segmented OpenBCI samples.

Reads outputs from split_segments.py and generates waveform QC figures:
1) Overview plot with multiple random segments.
2) Single-segment detail plot with ch1-4.
3) Channel sensitivity bar plot with anchor channel highlight.
"""

from __future__ import annotations

import argparse
import json
from pathlib import Path

import matplotlib.pyplot as plt
import numpy as np


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description="Visual QC for segmented OpenBCI samples")
    parser.add_argument(
        "--seg-dir",
        type=Path,
        default=Path("outputs/segmentation"),
        help="Directory generated by split_segments.py",
    )
    parser.add_argument(
        "--out-dir",
        type=Path,
        default=Path("outputs/visualizations"),
        help="Directory to write figures",
    )
    parser.add_argument(
        "--overview-count",
        type=int,
        default=6,
        help="How many segments to show in the overview figure (default: 6)",
    )
    parser.add_argument(
        "--specific-segments",
        type=str,
        default=None,
        help="Comma-separated List of specific segment IDs to visualize (e.g. '0,1,2,99'). Overrides --overview-count and --seed.",
    )
    parser.add_argument(
        "--seed",
        type=int,
        default=42,
        help="Random seed for reproducible segment sampling (ignored if specific-segments is used)",
    )
    return parser.parse_args()


def load_manifest(seg_dir: Path) -> dict:
    path = seg_dir / "manifest.json"
    if not path.exists():
        raise FileNotFoundError(f"Missing manifest: {path}. Run split_segments.py first.")
    return json.loads(path.read_text(encoding="utf-8"))


def plot_overview(direction: str, segments: np.ndarray, out_path: Path, count: int, seed: int, specific_ids: list[int] | None = None) -> list[int]:
    n_segments, seg_len, _ = segments.shape
    
    if specific_ids is not None:
        picked = [i for i in specific_ids if 0 <= i < n_segments]
        if not picked:
            picked = list(range(min(count, n_segments)))
    else:
        # User requested to default visualize the first 6 segments instead of random sample
        picked = list(range(min(count, n_segments)))

    fig, axes = plt.subplots(4, 1, figsize=(12, 9), sharex=True)
    x = np.arange(seg_len)
    for ch in range(4):
        for seg_id in picked:
            axes[ch].plot(x, segments[seg_id, :, ch], alpha=0.7, linewidth=1.0, label=f"seg{seg_id}")
        axes[ch].set_ylabel(f"ch{ch + 1}")
        axes[ch].grid(alpha=0.3)
    axes[-1].set_xlabel("sample index in segment")
    fig.suptitle(f"{direction} overview | segments={picked}")

    # Keep legend in the top axis to avoid clutter.
    handles, labels = axes[0].get_legend_handles_labels()
    if handles:
        axes[0].legend(handles, labels, fontsize=8, ncol=min(6, len(handles)), loc="upper right")

    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)
    return picked


def pick_detail_segment(segments: np.ndarray, anchor_channel: str) -> int:
    anchor_idx = int(anchor_channel.replace("ch", "")) - 1
    anchor_idx = max(0, min(anchor_idx, 3))
    # Pick the segment with highest RMS on the anchor channel for a representative detail plot.
    rms = np.sqrt(np.mean(np.square(segments[:, :, anchor_idx]), axis=1))
    return int(np.argmax(rms))


def plot_detail(direction: str, segments: np.ndarray, seg_id: int, out_path: Path) -> None:
    _, seg_len, _ = segments.shape
    x = np.arange(seg_len)

    fig, axes = plt.subplots(4, 1, figsize=(12, 9), sharex=True)
    for ch in range(4):
        axes[ch].plot(x, segments[seg_id, :, ch], linewidth=1.2)
        axes[ch].set_ylabel(f"ch{ch + 1}")
        axes[ch].grid(alpha=0.3)
    axes[-1].set_xlabel("sample index in segment")
    fig.suptitle(f"{direction} detail | segment={seg_id}")
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def plot_sensitivity(direction: str, channel_scores: dict[str, float], anchor_channel: str, out_path: Path) -> None:
    channels = ["ch1", "ch2", "ch3", "ch4"]
    values = [channel_scores.get(ch, 0.0) for ch in channels]
    colors = ["#d62728" if ch == anchor_channel else "#1f77b4" for ch in channels]

    fig, ax = plt.subplots(figsize=(7, 4))
    ax.bar(channels, values, color=colors)
    ax.set_title(f"{direction} channel sensitivity | anchor={anchor_channel}")
    ax.set_ylabel("95th percentile |x-median(x)|")
    ax.grid(axis="y", alpha=0.3)
    fig.tight_layout()
    fig.savefig(out_path, dpi=150)
    plt.close(fig)


def main() -> None:
    args = parse_args()
    manifest = load_manifest(args.seg_dir)
    args.out_dir.mkdir(parents=True, exist_ok=True)
    
    specific_ids = None
    if args.specific_segments:
        try:
            specific_ids = [int(x.strip()) for x in args.specific_segments.split(",")]
        except ValueError:
            print(f"Warning: Invalid format for --specific-segments: {args.specific_segments}. Taking first {args.overview_count} instead.")

    figure_manifest: dict[str, dict[str, object]] = {}
    for file_item in manifest["files"]:
        direction = file_item["direction"]
        anchor = file_item["anchor_channel"]
        channel_scores = file_item["channel_scores"]

        seg_path = Path(file_item["segments_path"])
        segments = np.load(seg_path)
        if segments.ndim != 3 or segments.shape[2] != 4:
            raise ValueError(f"Unexpected segment shape for {direction}: {segments.shape}")

        dir_out = args.out_dir / direction
        dir_out.mkdir(parents=True, exist_ok=True)

        overview_name = f"{direction}_overview_segments.png"
        detail_seg = specific_ids[0] if specific_ids and specific_ids[0] < segments.shape[0] else pick_detail_segment(segments, anchor)
        detail_name = f"{direction}_detail_seg{detail_seg}.png"
        sens_name = f"{direction}_sensitivity_anchor_{anchor}.png"

        picked = plot_overview(
            direction=direction,
            segments=segments,
            out_path=dir_out / overview_name,
            count=args.overview_count,
            seed=args.seed,
            specific_ids=specific_ids,
        )
        plot_detail(direction=direction, segments=segments, seg_id=detail_seg, out_path=dir_out / detail_name)
        plot_sensitivity(
            direction=direction,
            channel_scores=channel_scores,
            anchor_channel=anchor,
            out_path=dir_out / sens_name,
        )

        figure_manifest[direction] = {
            "overview": str(dir_out / overview_name),
            "overview_segment_ids": picked,
            "detail": str(dir_out / detail_name),
            "detail_segment_id": detail_seg,
            "sensitivity": str(dir_out / sens_name),
            "anchor_channel": anchor,
        }

    out_manifest = args.out_dir / "figure_manifest.json"
    out_manifest.write_text(json.dumps(figure_manifest, indent=2), encoding="utf-8")
    print(f"Done. Wrote visualizations to: {args.out_dir}")


if __name__ == "__main__":
    main()